package fnt.hu.nl.automatischNakijken.logic;

public enum TokenType {
	LPAREN, RPAREN, LACCOL, RACCOL, LCHEV, RCHEV,
	PUNC_PERIOD, PUNC_SEMICOLON, PUNC_COMMA,
	OP_EQUAL, OP_PLUS, OP_MINUS, OP_MOD, OP_MUL, OP_DIV,
	RW_CLASS, RW_EXTENDS, RW_IMPLEMENTS, RW_THIS,
	KW_RETURN, KW_VOID, KW_STRING, KW_INT, KW_LIST, KW_BOOL, KW_TRUE, KW_FALSE, 
	KW_CHAR,
	AM_PUBLIC, AM_PRIVATE, AM_PROTECTED,
	ATOM 
}
